include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_operations
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - close_sinks
    - comment_references
    - constant_evaluation
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - equal_greater_than
    - file_names
    - hash_and_equals
    - implementation_imports
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - no_leading_underscores_for_local_identifiers
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterables
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - provide_deprecation_message
    - sized_box_for_whitespace
    - sort_child_properties_last
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_final
    - unnecessary_getters_setters
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_operations
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unreachable_code
    - use_colored_box
    - use_const
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_rethrow_when_possible
    - use_super_args
    - void_checks

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
